on: [push]
name: Continuous Integration

jobs:
  inspect-code:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET 8.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore Tools
        run: dotnet tool restore

      - name: Restore Packages
        run: dotnet restore

      - name: Restore inspectcode cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/inspectcode
          key: inspectcode-${{ hashFiles('.config/dotnet-tools.json', '.github/workflows/ci.yml', 'osu.Game.Rulesets.Tau.sln*', '.editorconfig', '.globalconfig') }}

      - name: Dotnet code style
        run: dotnet build -c Debug osu.Game.Rulesets.Tau.sln -p:EnforceCodeStyleInBuild=true

      - name: InspectCode
        run: dotnet jb inspectcode $(pwd)/osu.Game.Rulesets.Tau.sln --no-build --output="inspectcodereport.xml" --caches-home="inspectcode" --verbosity=WARN

      - name: NVika
        run: dotnet nvika parsereport "${{github.workspace}}/inspectcodereport.xml"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: osu.Game.Rulesets.Tau.dll
          path: "osu.Game.Rulesets.Tau/bin/Debug/net8.0"
          retention-days: 90

  test:
    name: Test
    runs-on: ${{matrix.os.fullname}}
    env:
      OSU_EXECUTION_MODE: ${{matrix.threadingMode}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - { prettyname: Windows, fullname: windows-latest }
          - { prettyname: macOS, fullname: macos-latest }
          - { prettyname: Linux, fullname: ubuntu-latest }
        threadingMode: ['SingleThread', 'MultiThreaded']
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET 8.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x"

      - name: Compile
        run: dotnet build -c Debug -warnaserror osu.Game.Rulesets.Tau.sln

      - name: Test
        run: dotnet test $pwd/*.Tests/bin/Debug/*/*.Tests.dll --logger "trx;LogFileName=TestResults-${{matrix.os.prettyname}}-${{matrix.threadingMode}}.trx"
        shell: pwsh

      # Attempt to upload results even if test fails.
      # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#always
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: tau-test-results-${{matrix.os.prettyname}}-${{matrix.threadingMode}}
          path: ${{github.workspace}}/TestResults/TestResults-${{matrix.os.prettyname}}-${{matrix.threadingMode}}.trx
          retention-days: 90
